name: Storybook

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false # Ensure that previous runs aren't cancelled and leave the deployment in a broken state.

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    if: github.repository_owner == 'drivenets'

    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install

      - name: Build Storybook
        run: |
          pnpm run --filter @drivenets/design-system build:storybook
          cp -r ./packages/design-system/storybook-static /tmp/storybook-static

          LAST_COMMIT=$(git rev-parse --short HEAD)

          echo "LAST_COMMIT=$LAST_COMMIT" >> "$GITHUB_ENV"

      - name: Setup Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        run: |
          git checkout gh-pages
          rm -rf ./*
          cp -r /tmp/storybook-static/* ./

          git add .
          git commit -m "build: deploy storybook ($LAST_COMMIT)"
          git push

      # The `gh-pages` branch doesn't have the `.github/actions/install` directory, so we need to switch
      # back to the previous branch so the automatic "Post Install Dependencies" cleanup step will work.
      - name: Reset Branch
        run: git checkout -
